### ISSUE TITLE
09259_H_55 missing bait set

### ISSUE THREAD

**Issue by anoronh4** [mskcc/LimsRest#106]
I found a sample which was marked as igoComplete and has delivered fastqs but no baitSet listed -- the field is `""`. This is not necessarily a logical error but possibly misleading and most analysis of WES data would require some sort of baitSet identity. is there any reason the field is left empty, and is there any other logic we can use to fill in the info for baitSet? maybe there is an improvement to be made on the LIMS side to only deliver when info is complete?

maybe i'm missing something else here.

**Comment by dmcmanam** [comment]
That happens when there is an issue with stats generation being loaded back into the LIMS.  When stats are run on the cluster the bait set used is in that code and then we upload the stats into LIMS after the run is complete.  In some rare instances that upload has issues and the bait set could be blank, if you send me the IGO ID we'll correct it in LIMS.

**Comment by dmcmanam** [comment]
We have seen this error twice so far, at this point we have not had a chance to track down the source of the bug and are updating it manually in the LIMS so 09259_H_55 will now show the correct value.

**Comment by dmcmanam** [comment]
This seems to occur for very low quality samples where Picard stats fail.
